export const REASON_CODES = {
  VELOCITY_PATTERN: 'VELOCITY_PATTERN',
  THRESHOLD_AVOIDANCE: 'THRESHOLD_AVOIDANCE',
  HIGH_RISK_CUSTOMER: 'HIGH_RISK_CUSTOMER',
  MEDIUM_RISK_CUSTOMER: 'MEDIUM_RISK_CUSTOMER',
  KYC_INCOMPLETE: 'KYC_INCOMPLETE',
  NEW_ACCOUNT: 'NEW_ACCOUNT',
  STABLE_ACCOUNT: 'STABLE_ACCOUNT',
  LARGE_CASH_ACTIVITY: 'LARGE_CASH_ACTIVITY',
  MULTI_CHANNEL_MOVEMENT: 'MULTI_CHANNEL_MOVEMENT',
  MULTI_RULE_TRIGGER: 'MULTI_RULE_TRIGGER'
} as const;

export type ReasonCode = typeof REASON_CODES[keyof typeof REASON_CODES];